server:
  port: 8080
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enable: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
      show-sql: true
  flyway:
    user: sa
    password: ''
  config:
    import:
      - "application_qa.yml"
      - "application_prod.yml"
  profiles:
    active:
      - "local"

build:
  version: "3.0"

accounts:
  message: "Welcome to EasyBank accounts related local"
  contactDetails:
    name: "John Doe - Developer"
    email: "john@easybank.com"
    onCallSupport:
      -(555)555-1234
      -(555)523-1345




